---

- include: virtualenv.yml
- include: git_deploy.yml
  when: "{{ git_repo }}"
- include: tarball_deploy.yml
  when: "{{ package_tarball }}"
- include: dependencies.yml
- include: log.yml
- include: django.yml
  when: "{{ django_app }}"
- include: gunicorn.yml
