---

- name: Upload {{ package_name }} source package
  copy: src={{ package_tarball }} dest={{ package_root }}
  register: package_upload

- name: Install {{ package_name }} package
  pip: name={{ package_upload.dest }}[prod] virtualenv={{ virtualenv_root }}
